# permissions for end users to edit kubernetes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: kubernetes-editor-role
rules:
- apiGroups:
  - webapp.exemplo.com
  resources:
  - kubernetes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.exemplo.com
  resources:
  - kubernetes/status
  verbs:
  - get
