apiVersion: webapp.exemplo.com/v1
kind: Kubernetes
metadata:
  labels:
    app.kubernetes.io/name: kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: kubernetes-sample
spec:
  # TODO(user): Add fields here
